// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/position_service.proto

package position_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SavePositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imei          string                 `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	DeviceTime    int64                  `protobuf:"varint,2,opt,name=device_time,json=deviceTime,proto3" json:"device_time,omitempty"` // Unix timestamp
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed         int32                  `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Course        int32                  `protobuf:"varint,6,opt,name=course,proto3" json:"course,omitempty"`
	Attributes    string                 `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePositionRequest) Reset() {
	*x = SavePositionRequest{}
	mi := &file_proto_position_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePositionRequest) ProtoMessage() {}

func (x *SavePositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_position_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePositionRequest.ProtoReflect.Descriptor instead.
func (*SavePositionRequest) Descriptor() ([]byte, []int) {
	return file_proto_position_service_proto_rawDescGZIP(), []int{0}
}

func (x *SavePositionRequest) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *SavePositionRequest) GetDeviceTime() int64 {
	if x != nil {
		return x.DeviceTime
	}
	return 0
}

func (x *SavePositionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SavePositionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SavePositionRequest) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SavePositionRequest) GetCourse() int32 {
	if x != nil {
		return x.Course
	}
	return 0
}

func (x *SavePositionRequest) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

type SavePositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePositionResponse) Reset() {
	*x = SavePositionResponse{}
	mi := &file_proto_position_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePositionResponse) ProtoMessage() {}

func (x *SavePositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_position_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePositionResponse.ProtoReflect.Descriptor instead.
func (*SavePositionResponse) Descriptor() ([]byte, []int) {
	return file_proto_position_service_proto_rawDescGZIP(), []int{1}
}

func (x *SavePositionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SavePositionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_position_service_proto protoreflect.FileDescriptor

const file_proto_position_service_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/position_service.proto\x12\x0ftarget.position\"\xd2\x01\n" +
	"\x13SavePositionRequest\x12\x12\n" +
	"\x04imei\x18\x01 \x01(\tR\x04imei\x12\x1f\n" +
	"\vdevice_time\x18\x02 \x01(\x03R\n" +
	"deviceTime\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x05R\x05speed\x12\x16\n" +
	"\x06course\x18\x06 \x01(\x05R\x06course\x12\x1e\n" +
	"\n" +
	"attributes\x18\a \x01(\tR\n" +
	"attributes\"J\n" +
	"\x14SavePositionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2n\n" +
	"\x0fPositionService\x12[\n" +
	"\fSavePosition\x12$.target.position.SavePositionRequest\x1a%.target.position.SavePositionResponseB@Z>github.com/Caknoooo/go-gin-clean-starter/pkg/pb/position_protob\x06proto3"

var (
	file_proto_position_service_proto_rawDescOnce sync.Once
	file_proto_position_service_proto_rawDescData []byte
)

func file_proto_position_service_proto_rawDescGZIP() []byte {
	file_proto_position_service_proto_rawDescOnce.Do(func() {
		file_proto_position_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_position_service_proto_rawDesc), len(file_proto_position_service_proto_rawDesc)))
	})
	return file_proto_position_service_proto_rawDescData
}

var file_proto_position_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_position_service_proto_goTypes = []any{
	(*SavePositionRequest)(nil),  // 0: target.position.SavePositionRequest
	(*SavePositionResponse)(nil), // 1: target.position.SavePositionResponse
}
var file_proto_position_service_proto_depIdxs = []int32{
	0, // 0: target.position.PositionService.SavePosition:input_type -> target.position.SavePositionRequest
	1, // 1: target.position.PositionService.SavePosition:output_type -> target.position.SavePositionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_position_service_proto_init() }
func file_proto_position_service_proto_init() {
	if File_proto_position_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_position_service_proto_rawDesc), len(file_proto_position_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_position_service_proto_goTypes,
		DependencyIndexes: file_proto_position_service_proto_depIdxs,
		MessageInfos:      file_proto_position_service_proto_msgTypes,
	}.Build()
	File_proto_position_service_proto = out.File
	file_proto_position_service_proto_goTypes = nil
	file_proto_position_service_proto_depIdxs = nil
}
